### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by JeffBNimble** [thejoshwolfe/maze-generator#16]
Hi Josh,
I've been playing around with the demo and love that you've created this helpful library. I wonder if you would consider choosing one of the open source licenses and add to the project?

This site is one provided to me when I was asked to include a license on one of my repositories. http://choosealicense.com/

Thanks for sharing this library.

**Comment by thejoshwolfe** [comment]
Thanks for checking it out! I'd added the MIT License.

If I may ask, what interests you about this project? Educational uses? Game design? The academic theory behind it?

I've got all sorts of ideas on what to do next with this project, but I haven't had much motivation to work on it lately. Have you checked out the open issues? I'd like to know if any of those are particularly interesting to people. It may motivate me to make more progress on this project :)

**Comment by JeffBNimble** [comment]
Hi Josh,
Thank you for adding the license. I'm just wanting to play around and try to create a maze game on iOS. Interestingly, having worked at a game company for the past 7 years, I'm not a game programmer.

I've always wanted to try to create a game. I've always liked maze style games, so I did some research and found this article referenced in a StackOverflow post: http://www.astrolog.org/labyrnth/algrithm.htm. Somehow I stumbled across your library and some others and your demo piqued my interest. I looked at some other maze libraries and yours seemed the most complete, so I just grabbed it and started playing around with it.

I've looked over your issues and I don't yet have a firm grasp on everything yet, but the library as it is currently seems adequate for what I'm using it for.

I had to add my own "main.js" since I'm not running within a browser. I'm running inside of the JavaScriptCore context on iOS, which is a JS execution environment without a "window" object and no UI. So I had to make a few tweaks and have yet to try and tackle rendering yet since I'll be rendering natively on iOS and not in a web context.

Hopefully that gives you an idea of what I'm doing with your library. Thank you again for sharing it. It's really well done and the code is very clean and easy to read, though I've had to read up a bit on maze theory in general to understand.

**Comment by thejoshwolfe** [comment]
That article was a good read! it opened my eyes to lots of new maze analysis and maze generating ideas. that's really cool.

if you're making a game, i gotta say there's an awful lot of unnecessary code in this project if all you want to do is generate mazes. for example, the pattern of calling getOptions and then doOption instead of doing everything in a big loop: that's really only to support #14 (afaicr), and it's a waste of resources if you're not interested in the intermediate state information.

Of course, you're welcome to modify everything to suit your purposes. I'm just warning you that simplicity wasn't really an objective for this code, so there will probably be lots of stuff you'll want to delete.

Anyway, good luck with your project! Let me know if you have any questions about my code. I'd be happy to help explain things.

**Comment by JeffBNimble** [comment]
I have not jumped into the maze generation logic itself. However, I did look at the code you wrote which interacts with the generator to both generate the maze and calculate the longest path. I did write my own versions of that code to loop until finished in both cases.

I am certain I will have questions as I proceed through this. I'll try not to bug you too much, but appreciate the offer to help explain.

Thank you again for sharing and being open to assist.
